name: Publish image to Docker Hub
on: push
jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Check Docker version
              run: docker --version
            - name: build
              run: |
                docker build -f reviews.dockerfile -t shuaibu12345/reviews:latest .
            - name: publishing to docker hub
              run: |
                docker login -u shuaibu12345 -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push shuaibu12345/reviews:latest